### ISSUE TITLE
Could you make this work with Youtube on Chromecast?

### ISSUE THREAD

**Issue by bonelifer** [bdotq/pycast-mute-spot#1]
Could you make this work with Youtube on Chromecast? I can currently see the titles of my Youtube videos in the terminal. Would this be possible to adjust it to also work with YouTube?

**Comment by bdotq** [comment]
Pychromecast library already supports Chromecast. This script will also work with it.
You can modify [line 35](https://github.com/bdotq/pycast-mute-spot/blob/master/spotifyadmute_simple_listener.py#L35) for any keywords you want to use that show up in the title.
